### ISSUE TITLE
bert 分类报错

### ISSUE THREAD

**Issue by songsh** [shibing624/pytextclassifier#7]
bert 中文分类时 ，No module named 'simpletransformers'
fasttext 中文分类时，准确率不高，

**Comment by shibing624** [comment]
pip install simpletransformers发自我的iPhone------------------ 原始邮件 ------------------发件人: chendeming ***@***.***>发送时间: 2022年3月28日 16:39收件人: shibing624/pytextclassifier ***@***.***>抄送: Subscribed ***@***.***>主题: Re: [shibing624/pytextclassifier] bert 分类报错 (Issue #7)
bert 中文分类时 ，No module named 'simpletransformers'
fasttext 中文分类时，准确率不高，

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/shibing624/pytextclassifier/issues/7",
"url": "https://github.com/shibing624/pytextclassifier/issues/7",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by songsh** [comment]
感谢回复，用fasttext 分类时，运行两次，预测结果还不一样，是啥问题。

**Comment by shibing624** [comment]
差别大吗？case反馈下
